
services:
  backend:
    build:
      context: ./blog
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/blogdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: changemeinprod!
      JWT_SECRET: aB3o8+1lZK7M0XjzFtCz2t9mD6sYv7WaU2rXpHy+vUE=
    restart: always


  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changemeinprod!
      POSTGRES_DB: blogdb
    restart: always

  adminer:
    image: adminer:latest
    ports:
      - "8888:8080"
    restart: always